[package]
name = "protof"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3"
dirs = "5.0.1"
indicatif = "0.16.2"
colored = "2.0"